imports = [ "language.c" ]

[language.c]
compiler = "gcc"
libraries = ["libsForQt5.full", "libsForQt5.kirigami2", "libsForQt5.ki18n", "libsForQt5.knotifications", "libsForQt5.kconfigwidgets", "libsForQt5.kwindowsystem", "icu.dev", "tdlib", "zlib", "rlottie"]
includes = ["libsForQt5.full", "libsForQt5.kirigami2", "libsForQt5.ki18n", "libsForQt5.knotifications", "libsForQt5.kconfigwidgets", "libsForQt5.kwindowsystem", "icu.dev", "tdlib", "zlib", "rlottie"]

[devshell]
name = "tok-devshell"
packages = [ "cmake", "binutils", "jq" ]

# qbs needs a writable home
[devshell.startup.setTmpHome]
text = """
if [ ! -w "$HOME" ] ; then
    export HOME=/tmp/tok-tmp-build-home/
    mkdir -p $HOME
fi
"""

[devshell.startup.setupQbs]
text = """
qbs setup-toolchains --detect
qbs resolve profile:gcc
"""
deps = ["setTmpHome"]

# workaround for devshell not setting LIBRARY_PATH
[[env]]
name = "LIBRARY_PATH"
eval = "$DEVSHELL_DIR/lib"

[[commands]]
package = "qbs"
